Repository kysely-org/kysely, pull requests merged in 2022-10, with the labels that each got.

#169 add `DynamicReferenceBuilder` support @ `FunctionModule`.
  src/index.ts
  src/operation-node/aggregate-function-node.ts
  src/operation-node/operation-node-utils.ts
  src/operation-node/partition-by-item-node.ts
  src/parser/reference-parser.ts
  src/query-builder/function-module.ts
  test/node/src/aggregate-function.test.ts
  test/typings/test-d/function-module.test-d.ts
Labels: enhancement

#181 add `kysely-singlestore` to 3rd party dialects @ readme.md.
  README.md
Labels: documentation

#193 fix CamelCasePlugin canMap mistakenly mapping ArrayBufferLikes.
  src/plugin/camel-case/camel-case-plugin.ts
  src/util/object-utils.ts
Labels: bug

#194 fix bigint `n` notation not buildable in some targets.
  src/dialect/postgres/postgres-adapter.ts
Labels: bug

#200 fix(types): make `sql.ids(...)` & `sql.join(...)` arguments readonly
  src/raw-builder/sql.ts
Labels: enhancement, typescript

#179 add `db.fn.coalesce(...)`
  src/parser/coalesce-parser.ts
  src/query-builder/function-module.ts
  test/node/src/coalesce.test.ts
  test/typings/test-d/coalesce.test-d.ts
Labels: enhancement, api

#183 make `FunctionModule`'s `avg`, `max`, `min` & `sum` functions nullable (consumer opt-in).
  src/query-builder/function-module.ts
  test/typings/test-d/coalesce.test-d.ts
  test/typings/test-d/function-module.test-d.ts
Labels: enhancement, typescript

#202 fix no separator between default insert values.
  src/query-compiler/default-query-compiler.ts
  test/node/src/insert.test.ts
  test/node/src/introspect.test.ts
  test/node/src/test-setup.ts
Labels: bug

#210 `exactOptionalPropertyTypes` should no longer error when updating/inserting with undefined values in nullable columns.
  src/parser/insert-values-parser.ts
  src/parser/update-set-parser.ts
  test/typings/test-d/index.test-d.ts
  test/typings/tsconfig.json
Labels: enhancement, api, typescript
