Repository kysely-org/kysely, pull requests merged in 2022-11, with the labels that each got.

#201 add `modifyFront` & `modifyEnd` @ `ColumnDefinitionBuilder`, `AlterTableAddColumnBuilder` & `AlterTableModifyColumnBuilder`.
  src/operation-node/column-definition-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/alter-table-builder.ts
  src/schema/column-definition-builder.ts
  src/schema/create-table-builder.ts
  test/node/src/schema.test.ts
Labels: enhancement, api

#220 fix migrationKey calculation keeping dot when .mjs @ `FileMigrationProvider`.
  src/migration/file-migration-provider.ts
Labels: bug, enhancement

#226 Add additional column in PostgreSQL migration example to showcase defaultTo
  README.md
Labels: documentation, postgres

#222 fix `FunctionModule.max` & `FunctionModule.min` autocompletion.
  src/index.ts
  src/query-builder/function-module.ts
  src/util/type-utils.ts
  test/typings/shared.d.ts
  test/typings/test-d/function-module.test-d.ts
  test/typings/test-d/infer-result.test-d.ts
Labels: bug, typescript

#225 add module augmentation section to extending-kysely recipe.
  recipes/extending-kysely.md
Labels: documentation

#215 add `CONTRIBUTING.md`.
  CONTRIBUTING.md
  README.md
Labels: documentation
