Repository kysely-org/kysely, pull requests merged in 2022-12, with the labels that each got.

#236 fix: trim sql row to remove leading whitespace or newline
  src/dialect/sqlite/sqlite-introspector.ts
Labels: bug, sqlite, built-in dialect

#238 feat(alter-table): support multiple column operations
  src/index.ts
  src/operation-node/alter-table-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/alter-column-builder.ts
  src/schema/alter-table-builder.ts
  src/schema/column-definition-builder.ts
  src/schema/schema.ts
  test/node/src/schema.test.ts
Labels: enhancement, api, breaking change

#188 add `numInsertedOrUpdatedRows` to `InsertResult`.
  src/dialect/mysql/mysql-driver.ts
  src/dialect/postgres/postgres-driver.ts
  src/dialect/sqlite/sqlite-driver.ts
  src/driver/database-connection.ts
  src/index.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/insert-result.ts
  src/query-builder/update-query-builder.ts
  src/query-executor/query-executor-base.ts
  src/util/log-once.ts
  test/node/src/delete.test.ts
  test/node/src/insert.test.ts
  test/node/src/log-once.test.ts
  test/node/src/update.test.ts
Labels: bug, enhancement, api, deprecation

#208 add `filter` clause support at `AggregateFunctionBuilder`.
  src/operation-node/aggregate-function-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-builder/where-interface.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/aggregate-function.test.ts
  test/node/src/postgres-json.test.ts
  test/typings/test-d/function-module.test-d.ts
Labels: enhancement, sqlite, postgres, api

#259 chore: fix typo
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
Labels: documentation

#256 add clearSelect/Where/OrderBy/Limit/Offset
  src/operation-node/on-conflict-node.ts
  src/operation-node/query-node.ts
  src/operation-node/select-query-node.ts
  src/parser/select-parser.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/on-conflict-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/query-builder/where-interface.ts
  src/raw-builder/sql.ts
  test/node/src/clear.test.ts
  test/typings/test-d/clear.test-d.ts
Labels: enhancement, api
