Repository kysely-org/kysely, pull requests merged in 2023-07, with the labels that each got.

#556 chore: add new tweets, fix some titles, re-organize.
  site/src/pages/index.tsx
  site/static/img/avatars/benholmes.jpeg
  site/static/img/avatars/pilcrowonpaper.jpeg
Labels: documentation

#558 Add `regexp` comparison operator
  src/operation-node/operator-node.ts
Labels: enhancement, mysql, sqlite, api, typescript

#560 Update outdated alterColumn function call example
  src/schema/schema.ts
Labels: documentation

#446 docs: use methods from expression builder callback instead of global instance
  src/expression/expression-builder.ts
  src/expression/expression-wrapper.ts
  src/kysely.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-builder/function-module.ts
  src/query-builder/over-builder.ts
  src/query-builder/returning-interface.ts
  src/query-builder/select-query-builder.ts
Labels: documentation

#562 docs: fix introspecting relation metadata example
  site/docs/recipes/introspecting-relation-metadata.md
Labels: documentation

#557 site: video dimensions for different screen sizes
  site/src/components/DemoVideo.module.css
  site/src/components/DemoVideo.tsx
  site/src/pages/index.tsx
Labels: documentation

#563 add Ross' tweet.
  site/src/pages/index.tsx
  site/static/img/avatars/ross.jpeg
Labels: documentation, ready for review

#431 Add UpdateResult.numChangedRows
  src/dialect/database-introspector.ts
  src/dialect/mysql/mysql-dialect-config.ts
  src/dialect/mysql/mysql-driver.ts
  src/driver/database-connection.ts
  src/parser/update-set-parser.ts
  src/query-builder/update-query-builder.ts
  src/query-builder/update-result.ts
  test/node/src/update.test.ts
Labels: enhancement, mysql, api, ready for review

#525 test deno with real drivers.
  .github/workflows/test.yml
  package.json
  test/deno/cdn.test.ts
  test/deno/deno.json
  test/deno/deno.lock
  test/deno/local.test.ts
Labels: ready for review

#526 bun test.
  .github/workflows/test.yml
  package.json
  test/bun/bun.lockb
  test/bun/bun.test.ts
  test/bun/package.json
Labels: ready for review

#568 fix `onConflict` compilation errors since TS 5.1.6.
  package-lock.json
  package.json
  src/query-builder/insert-query-builder.ts
Labels: bug, typescript

#565 Expression builder v2
  src/dialect/postgres/postgres-introspector.ts
  src/dynamic/dynamic.ts
  src/expression/expression-builder.ts
  src/expression/expression-wrapper.ts
  src/operation-node/alter-column-node.ts
  src/operation-node/join-node.ts
  src/operation-node/operator-node.ts
  src/operation-node/query-node.ts
  src/operation-node/select-query-node.ts
  src/parser/binary-operation-parser.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-builder/case-builder.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/deprecated-having-expression-builder.ts
  src/query-builder/deprecated-on-expression-builder.ts
  src/query-builder/deprecated-where-expression-builder.ts
  src/query-builder/function-module.ts
  src/query-builder/having-interface.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/join-builder.ts
  src/query-builder/on-conflict-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/query-builder/where-interface.ts
  src/schema/alter-column-builder.ts
  src/schema/alter-table-builder.ts
  src/schema/create-index-builder.ts
  src/schema/create-table-builder.ts
  test/node/src/aggregate-function.test.ts
  test/node/src/case.test.ts
  test/node/src/delete.test.ts
  test/node/src/expression.test.ts
  test/node/src/having.test.ts
  test/node/src/join.test.ts
  test/node/src/raw-sql.test.ts
  test/node/src/schema.test.ts
  test/node/src/where.test.ts
  test/node/src/with.test.ts
  test/typings/test-d/case.test-d.ts
  test/typings/test-d/delete-query-builder.test-d.ts
  test/typings/test-d/expression.test-d.ts
  test/typings/test-d/kysely-any.test-d.ts
  test/typings/test-d/where.test-d.ts
Labels: enhancement, api, breaking change

#573 Add more quotes.
  site/src/pages/index.tsx
  site/static/img/avatars/alexanderson.jpeg
  site/static/img/avatars/codemonument.jpeg
  site/static/img/avatars/julius.jpeg
  site/static/img/avatars/leerob.jpeg
  site/static/img/avatars/nexxel.jpeg
  site/static/img/avatars/orta.jpeg
  site/static/img/avatars/sock.jpeg
Labels: documentation, blocked

#576 Fix typo
  src/kysely.ts
Labels: documentation

#578 Support materialized CTEs using CTE builder
  src/operation-node/common-table-expression-node.ts
  src/operation-node/operation-node-transformer.ts
  src/parser/join-parser.ts
  src/parser/with-parser.ts
  src/query-builder/cte-builder.ts
  src/query-compiler/default-query-compiler.ts
  src/query-creator.ts
  test/node/src/with.test.ts
  test/typings/test-d/with.test-d.ts
Labels: enhancement, postgres, api

#581 Allow expression builder in set operations. Closes #285
  src/parser/expression-parser.ts
  src/parser/set-operation-parser.ts
  src/query-builder/select-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/set-operation.test.ts
Labels: enhancement, mysql, postgres, api

#574 add cloudflare workers test.
  .github/workflows/test.yml
  package.json
  test/cloudflare-workers/.dev.vars
  test/cloudflare-workers/api.ts
  test/cloudflare-workers/package-lock.json
  test/cloudflare-workers/package.json
  test/cloudflare-workers/test.ts
Labels: tests

#582 when traversing `Record<string, T>`, infer output type as `Nullable<T>`.
  src/query-builder/json-path-builder.ts
  test/typings/shared.d.ts
  test/typings/test-d/json-traversal.test-d.ts
Labels: enhancement, api, typescript

#583 add object support for 'and' and 'or' functions. Closes #344
  site/docs/examples/WHERE/0040-or-where.js
  site/docs/examples/WHERE/0040-or-where.mdx
  site/docs/examples/WHERE/0050-conditional-where-calls.js
  site/docs/examples/WHERE/0050-conditional-where-calls.mdx
  site/docs/examples/WHERE/0060-complex-where-clause.js
  site/docs/examples/WHERE/0060-complex-where-clause.mdx
  src/expression/expression-builder.ts
  src/index.ts
  src/parser/binary-operation-parser.ts
  src/query-builder/where-interface.ts
  test/node/src/expression.test.ts
  test/node/src/where.test.ts
  test/typings/test-d/expression.test-d.ts
Labels: enhancement, api

#585 docs: sqlite dialect updated import
  site/docs/getting-started/Instantiation.tsx
Labels: documentation

#587 docs: sqlite migration example
  site/docs/migrations.mdx
Labels: documentation

#589 Convert `SelectQueryBuilder` and `RawBuilder` to interfaces
  scripts/generate-site-examples.js
  src/expression/expression-builder.ts
  src/parser/parse-utils.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/having-interface.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/where-interface.ts
  src/query-creator.ts
  src/raw-builder/raw-builder.ts
  src/raw-builder/sql.ts
Labels: bug, api, typescript

#590 Support boolean subqueries in addition to boolean expressions in filters
  src/expression/expression-builder.ts
  src/expression/expression-wrapper.ts
  src/index.ts
  src/parser/expression-parser.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/having-interface.ts
  src/query-builder/join-builder.ts
  src/query-builder/on-conflict-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/query-builder/where-interface.ts
  src/schema/create-index-builder.ts
  test/node/src/raw-sql.test.ts
  test/node/src/where.test.ts
  test/typings/test-d/where.test-d.ts
Labels: bug, enhancement, typescript, breaking change

#591 add Orta and Tim Grissier quotes.
  site/src/pages/index.tsx
  site/static/img/avatars/tgriesser.jpeg
Labels: documentation, ready for review

#423 add multi-column invocations & `${ref} ${direction}` @ `.orderBy`.
  package-lock.json
  src/operation-node/delete-query-node.ts
  src/operation-node/order-by-node.ts
  src/operation-node/over-node.ts
  src/operation-node/select-query-node.ts
  src/parser/order-by-parser.ts
  src/parser/reference-parser.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/over-builder.ts
  src/query-builder/select-query-builder.ts
  test/node/src/order-by.test.ts
  test/typings/test-d/index.test-d.ts
Labels: enhancement, api, ready for review

#598 parse json recursively in ParseJsonResultsPlugin
  src/plugin/camel-case/camel-case-plugin.ts
  src/plugin/parse-json-results/parse-json-results-plugin.ts
  src/util/object-utils.ts
Labels: enhancement, built-in plugin

#600 Add `lit` method to expression builder
  src/expression/expression-builder.ts
  test/node/src/expression.test.ts
  test/node/src/where.test.ts
  test/typings/test-d/expression.test-d.ts
Labels: enhancement, api

#602 Add between method to expression builder
  src/expression/expression-builder.ts
  src/operation-node/operator-node.ts
  src/query-builder/having-interface.ts
  src/query-builder/join-builder.ts
  src/query-builder/where-interface.ts
  src/schema/alter-table-builder.ts
  src/schema/column-definition-builder.ts
  test/node/src/expression.test.ts
  test/typings/test-d/expression.test-d.ts
Labels: enhancement, mysql, sqlite, postgres, api

#606 Support arrays in set operations
  src/operation-node/select-query-node.ts
  src/parser/set-operation-parser.ts
  src/query-builder/select-query-builder.ts
  test/node/src/set-operation.test.ts
  test/typings/test-d/set-operation.test-d.ts
Labels: enhancement, api

#605 Support select queries without from clause
  src/expression/expression-builder.ts
  src/operation-node/select-query-node.ts
  src/parser/parse-utils.ts
  src/plugin/camel-case/camel-case-plugin.ts
  src/query-compiler/default-query-compiler.ts
  src/query-creator.ts
  test/node/src/select.test.ts
  test/typings/test-d/expression.test-d.ts
  test/typings/test-d/select-no-from.test-d.ts
Labels: enhancement, api

#612 Add `any` function to the function module
  src/expression/expression-builder.ts
  src/parser/value-parser.ts
  src/query-builder/function-module.ts
  test/node/src/array.test.ts
  test/node/src/expression.test.ts
  test/node/src/where.test.ts
  test/typings/shared.d.ts
  test/typings/test-d/expression.test-d.ts
Labels: enhancement, mysql, postgres, api, breaking change

#611 Support tuples
  src/expression/expression-builder.ts
  src/index.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/operation-node.ts
  src/operation-node/tuple-node.ts
  src/parser/select-parser.ts
  src/parser/tuple-parser.ts
  src/query-builder/select-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  src/util/column-type.ts
  src/util/type-utils.ts
  test/node/src/select.test.ts
  test/node/src/where.test.ts
  test/typings/test-d/expression.test-d.ts
Labels: enhancement, mysql, sqlite, postgres, api
