Repository kysely-org/kysely, pull requests merged in 2023-11, with the labels that each got.

#742 Update generating-types.md
  site/docs/generating-types.md
Labels: documentation

#759 feat(docs): capacitor sqlite driver
  site/docs/dialects.md
Labels: documentation, custom dialect, sqlite

#747 fix errors for contributors on Windows
  package-lock.json
  package.json
  scripts/module-fixup.js
Labels: ready for review, tests

#770 Nulls not distinct option
  src/operation-node/column-definition-node.ts
  src/operation-node/create-index-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/unique-constraint-node.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/alter-table-builder.ts
  src/schema/column-definition-builder.ts
  src/schema/create-index-builder.ts
  src/schema/create-table-builder.ts
  src/schema/unique-constraint-builder.ts
  test/node/src/schema.test.ts
  test/typings/test-d/alter-table.test-d.ts
  test/typings/test-d/create-table.test-d.ts
Labels: enhancement, postgres, api

#720 add `addIndex` & `dropIndex` @ `AlterTableBuilder`
  src/operation-node/add-index-node.ts
  src/operation-node/alter-table-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/operation-node.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/alter-table-add-index-builder.ts
  src/schema/alter-table-builder.ts
  test/node/src/schema.test.ts
Labels: enhancement, mysql, api, ready for review

#754 feat: add stream() support for sqlite dialect
  src/dialect/sqlite/sqlite-dialect-config.ts
  src/dialect/sqlite/sqlite-driver.ts
  test/node/src/select.test.ts
Labels: enhancement, sqlite, built-in dialect, ready for review
