Repository kysely-org/kysely, pull requests merged in 2023-08, with the labels that each got.

#635 Add SQLocal to 3rd party dialects list
  site/docs/dialects.md
Labels: documentation

#640 Add Deno SQLite to community dialects
  site/docs/dialects.md
Labels: documentation, custom dialect, sqlite

#639 Add addPrimaryKeyConstraint for AlterTableBuilder
  src/schema/alter-table-builder.ts
  test/node/src/schema.test.ts
Labels: enhancement, mysql, postgres, api

#645 fix node-postgres `pool` link
  src/dialect/postgres/postgres-dialect-config.ts
Labels: documentation

#660 Add Xata as a dialect
  site/docs/dialects.md
Labels: documentation

#669 Fix Node.js stack traces when code in a transaction throws
  src/driver/single-connection-provider.ts
  test/node/src/transaction.test.ts
Labels: bug
