Repository kysely-org/kysely, pull requests merged in 2023-12, with the labels that each got.

#806 add dialect specific truncate snippet for sqlite
  site/docs/getting-started/Summary.tsx
Labels: documentation

#807 fix sqlite created_at column type typo
  site/docs/getting-started/Summary.tsx
Labels: documentation

#796 fix: query and error logging both occur on error.
  src/driver/runtime-driver.ts
  src/util/log.ts
  test/node/src/log-once.test.ts
  test/node/src/logging.test.ts
Labels: bug, ready for review

#793 fix: `$if` inside `with` is `{ [x: string]: any }[]`.
  src/query-builder/select-query-builder.ts
  test/typings/test-d/with.test-d.ts
Labels: bug, typescript, ready for review

#818 add mssql json helpers.
  package.json
  src/helpers/mssql.ts
  test/node/src/json.test.ts
  test/node/src/test-setup.ts
Labels: enhancement, helpers, mssql

#795 fix: `ExpressionBuilder.fn.max`/`ExpressionBuilder.fn.min` signature type complexity breaks in complex `with` example.
  src/query-builder/function-module.ts
  test/typings/test-d/aggregate-function.test-d.ts
Labels: bug, typescript, ready for review

#792 fix: `onConflict..doUpdateSet` using select types instead of update types.
  src/query-builder/on-conflict-builder.ts
  test/typings/shared.d.ts
  test/typings/test-d/delete-query-builder.test-d.ts
  test/typings/test-d/index.test-d.ts
  test/typings/test-d/insert.test-d.ts
  test/typings/test-d/join.test-d.ts
  test/typings/test-d/select-from.test-d.ts
  test/typings/test-d/select.test-d.ts
Labels: bug, postgres, typescript, ready for review

#791 add `eb.jsonPath<$>`.
  src/expression/expression-builder.ts
  src/query-builder/json-path-builder.ts
  test/node/src/json-traversal.test.ts
  test/typings/test-d/json-traversal.test-d.ts
Labels: enhancement, api, ready for review

#724 Mssql docs
  package-lock.json
  site/docs/dialects.md
  site/docs/getting-started/Dialects.tsx
  site/docs/getting-started/Installation.tsx
  site/docs/getting-started/Instantiation.tsx
  site/docs/getting-started/Querying.tsx
  site/docs/getting-started/Summary.tsx
  site/docs/getting-started/_types.mdx
  site/docs/getting-started/shared.tsx
  site/package-lock.json
  site/package.json
Labels: documentation, mssql

#824 Fix regression Node 14
  src/dialect/mssql/mssql-introspector.ts
Labels: bug, built-in dialect, mssql
