Repository kysely-org/kysely, pull requests merged in 2023-05, with the labels that each got.

#458 Chore(docs): Missing comma in dynamic.ts
  src/dynamic/dynamic.ts
Labels: documentation

#457 add more tweets to site.
  site/src/pages/index.tsx
Labels: documentation

#463 Added column type binary(${number})
  src/operation-node/data-type-node.ts
  test/node/src/schema.test.ts
Labels: enhancement, mysql, api, typescript

#471 Fix alterTable table name parsing
  src/operation-node/alter-table-node.ts
  src/schema/schema.ts
  test/node/src/schema.test.ts
Labels: bug, postgres, api

#404 add `case` statements/operators.
  src/expression/expression-builder.ts
  src/index.ts
  src/kysely.ts
  src/operation-node/case-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/operation-node.ts
  src/operation-node/when-node.ts
  src/parser/binary-operation-parser.ts
  src/query-builder/case-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/case.test.ts
  test/node/src/introspect.test.ts
  test/node/src/test-setup.ts
  test/typings/shared.d.ts
  test/typings/test-d/case.test-d.ts
  test/typings/test-d/delete-query-builder.test-d.ts
  test/typings/test-d/join.test-d.ts
  test/typings/test-d/select-from.test-d.ts
Labels: enhancement, mysql, sqlite, postgres, api

#417 add `agg` method @ `FunctionModule` to allow `AggregateFunctionBuilder` usage outside of built-ins.
  src/operation-node/aggregate-function-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-builder/function-module.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/aggregate-function.test.ts
Labels: enhancement, api, breaking change

#464 fix `fn.max`/`fn.min` not usable as `fn(...)` arguments.
  src/query-builder/function-module.ts
  src/util/type-utils.ts
  test/typings/test-d/aggregate-function.test-d.ts
Labels: bug, typescript

#484 readme badge pass.
  README.md
Labels: documentation

#483 feat: increase fault tolerance to deep types error
  src/dialect/mysql/mysql-dialect-config.ts
  src/parser/expression-parser.ts
  src/parser/select-parser.ts
  src/parser/table-parser.ts
  src/parser/with-parser.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/schema/create-index-builder.ts
  src/util/column-type.ts
  src/util/object-utils.ts
  src/util/type-utils.ts
  test/typings/test-d/with.test-d.ts
Labels: enhancement, typescript

#478 Workaround obscure RDS Data Api Bug
  src/dialect/postgres/postgres-introspector.ts
Labels: enhancement, custom dialect, postgres, built-in dialect

#499 add 'bytea' to column data types.
  src/operation-node/data-type-node.ts
  test/node/src/schema.test.ts
Labels: enhancement, postgres, typescript

#512 feat(sql.raw): Allow parameters in raw sql
  src/query-compiler/compiled-query.ts
  test/node/src/raw-sql.test.ts
Labels: enhancement, api

#468 fix: disallow AlterColumn method chaining
  src/operation-node/alter-column-node.ts
  src/schema/alter-column-builder.ts
  src/schema/alter-table-builder.ts
Labels: bug, mysql, postgres, api
