Repository kysely-org/kysely, pull requests merged in 2023-01, with the labels that each got.

#241 add `using` clause support @ `DeleteQueryBuilder`.
  src/index.ts
  src/operation-node/delete-query-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/operation-node.ts
  src/operation-node/using-node.ts
  src/query-builder/delete-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/delete.test.ts
  test/typings/shared.d.ts
  test/typings/test-d/delete-query-builder.test-d.ts
  test/typings/test-d/index.test-d.ts
Labels: enhancement, mysql, postgres, api

#276 Fix FileMigrationProvider example
  src/migration/migrator.ts
Labels: documentation

#273 Introspect views
  recipes/README.md
  recipes/introspecting-relation-metadata.md
  src/dialect/database-introspector.ts
  src/dialect/mysql/mysql-introspector.ts
  src/dialect/postgres/postgres-introspector.ts
  src/dialect/sqlite/sqlite-introspector.ts
  test/node/src/introspect.test.ts
Labels: enhancement, mysql, sqlite, postgres, built-in dialect, api, breaking change

#267 add `FunctionModule.countAll(...)`.
  src/operation-node/aggregate-function-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-builder/function-module.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/aggregate-function.test.ts
  test/typings/test-d/function-module.test-d.ts
Labels: documentation, enhancement, mysql, sqlite, postgres, api

#294 fix: change qb to db in innerJoin docs example
  src/query-builder/select-query-builder.ts
Labels: documentation

#292 fix `AliasedRawBuilder` being parsed as `ValueNode` instead of `RawNode`.
  src/parser/expression-parser.ts
  test/node/src/raw-sql.test.ts
Labels: bug

#290 Fix missing quotes in typedoc
  src/query-builder/select-query-builder.ts
Labels: documentation
