Repository kysely-org/kysely, pull requests merged in 2023-04, with the labels that each got.

#416 feat: support `char` datatype
  src/operation-node/data-type-node.ts
  test/node/src/schema.test.ts
Labels: enhancement, mysql, postgres, api, typescript

#375 add column sort order @ `CreateIndexBuilder`.
  src/operation-node/create-index-node.ts
  src/operation-node/operation-node-transformer.ts
  src/parser/order-by-parser.ts
  src/parser/reference-parser.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/create-index-builder.ts
  test/node/src/schema.test.ts
Labels: enhancement, mysql, sqlite, postgres, api

#380 add `.$narrowType` @ `SelectQueryBuilder`, `InsertQueryBuilder`, `UpdateQueryBuilder` & `DeleteQueryBuilder`.
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/util/type-utils.ts
Labels: enhancement, api, typescript

#424 update site tweets.
  package-lock.json
  site/src/pages/index.tsx
Labels: documentation

#419 align 3rd party dialects.
  README.md
  site/docs/dialects.md
  site/docs/installation.md
Labels: documentation

#425 feature: Make logger support async calls
  src/driver/runtime-driver.ts
  src/util/log.ts
Labels: enhancement, api

#426 docs(README): remove sponsors header
  README.md
Labels: documentation

#427 better contributors section @ README.md.
  README.md
Labels: documentation

#438 fix incorrect usage of `.returning` in jsdocs.
  src/kysely.ts
Labels: bug, documentation

#448 add Mehul Mohan's tweet.
  site/src/pages/index.tsx
Labels: documentation

#439 align docs site generating types section with readme.
  site/docs/generating-types.md
Labels: documentation
