Repository kysely-org/kysely, pull requests merged in 2023-03, with the labels that each got.

#347 Add sqld dialect
  README.md
Labels: documentation

#324 Update `executeTakeFirstOrThrow` to allow throwing custom error objects
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/no-result-error.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  test/node/src/execute.test.ts
Labels: enhancement, api

#364 add `Kysely.executeQuery`.
  recipes/splitting-build-compile-and-execute-code.md
  src/kysely.ts
  src/query-executor/query-executor.ts
  src/util/compilable.ts
  test/node/src/execute.test.ts
Labels: enhancement, api

#365 add `RawBuilder.compile`.
  recipes/splitting-build-compile-and-execute-code.md
  src/raw-builder/raw-builder.ts
  test/node/src/raw-query.test.ts
Labels: enhancement, api

#366 add `prisma-kysely` to README.md.
  README.md
Labels: documentation

#371 add `.where` & `.orWhere` @ `CreateIndexBuilder`.
  src/operation-node/create-index-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/query-node.ts
  src/parser/binary-operation-parser.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/create-index-builder.ts
  test/node/src/schema.test.ts
Labels: enhancement, sqlite, postgres, api

#379 add kysely-s3-select dialect to README.md.
  README.md
Labels: documentation

#327 Documentation site
  README.md
  recipes/README.md
  recipes/excessively-deep-types.md
  site/.gitignore
  site/babel.config.js
  site/docs/dialects.md
  site/docs/examples/DELETE/_category_.json
  site/docs/examples/DELETE/delete-by-id.mdx
  site/docs/examples/INSERT/_category_.json
  site/docs/examples/INSERT/insert-many.mdx
  site/docs/examples/SELECT/_category_.json
  site/docs/examples/SELECT/find-by-age.mdx
  site/docs/examples/SELECT/find-by-id.mdx
  site/docs/examples/SELECT/find-multiple-by-id.mdx
  site/docs/examples/SELECT/join.mdx
  site/docs/examples/SELECT/left-outer-join.png
  site/docs/examples/UPDATE/_category_.json
  site/docs/examples/UPDATE/update-by-id.mdx
  site/docs/examples/_category_.json
  site/docs/generating-types.md
  site/docs/installation.md
  site/docs/intro.md
  site/docs/migrations.mdx
  site/docs/playground.mdx
  site/docs/plugins.md
  site/docs/recipes/_category_.json
  site/docs/recipes/conditional-selects.md
  site/docs/recipes/deduplicate-joins.md
  site/docs/recipes/excessively-deep-types.md
  site/docs/recipes/extending-kysely.md
  site/docs/recipes/introspecting-relation-metadata.md
  site/docs/recipes/raw-sql.md
  site/docs/recipes/schemas.md
  site/docs/recipes/splitting-build-compile-and-execute-code.md
  site/docs/runtimes/_category_.json
  site/docs/runtimes/browser.md
  site/docs/runtimes/deno.mdx
  site/docusaurus.config.js
  site/package-lock.json
  site/package.json
  site/sidebars.js
  site/src/components/Playground.tsx
  site/src/components/SectionFeatures/index.tsx
  site/src/components/SectionFeatures/styles.module.css
  site/src/css/custom.css
  site/src/pages/index.module.css
  site/src/pages/index.tsx
  site/static/.nojekyll
  site/static/img/docusaurus.png
  site/static/img/favicon.ico
  site/static/img/logo.svg
  site/static/img/undraw_docusaurus_mountain.svg
  site/static/img/undraw_docusaurus_react.svg
  site/static/img/undraw_docusaurus_tree.svg
  site/tsconfig.json
Labels: documentation

#386 fix Dax Raad's profile pic in docs.
  site/src/pages/index.tsx
Labels: documentation

#387 fix broken links in the site
  site/docs/dialects.md
  site/docs/intro.md
  site/docs/migrations.mdx
  site/docs/plugins.md
  site/docs/recipes/conditional-selects.md
  site/docs/recipes/deduplicate-joins.md
  site/docs/recipes/excessively-deep-types.md
  site/docs/recipes/extending-kysely.md
  site/docs/recipes/introspecting-relation-metadata.md
  site/docs/recipes/raw-sql.md
  site/docs/recipes/schemas.md
  site/docusaurus.config.js
  site/src/pages/index.tsx
Labels: documentation

#377 add `.stream` @ `InsertQueryBuilder`, `UpdateQueryBuilder` & `DeleteQueryBuilder`.
  src/index.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/util/streamable.ts
  test/node/src/delete.test.ts
  test/node/src/insert.test.ts
  test/node/src/test-setup.ts
  test/node/src/update.test.ts
Labels: enhancement, postgres, api

#378 DRY up `explain` docs and clone logic.
  src/operation-node/delete-query-node.ts
  src/operation-node/query-node.ts
  src/operation-node/select-query-node.ts
  src/operation-node/update-query-node.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/util/explainable.ts
Labels: documentation

#392 feat: implemented vercel's requirements to apply for the OSS plan
  README.md
  site/docusaurus.config.js
  site/static/img/powered-by-vercel.svg
Labels: documentation

#391 Add relations recipe
  README.md
  site/docs/recipes/relations.md
Labels: documentation

#390 Expression recipe and some simple tests
  README.md
  site/docs/recipes/expressions.md
  test/node/src/expression.test.ts
  test/typings/test-d/expression.test-d.ts
Labels: documentation

#401 Fix playground iframe.
  site/src/components/Playground.tsx
Labels: documentation
