Repository kysely-org/kysely, pull requests merged in 2024-09, with the labels that each got.

#1139 Updated TraversedJSONPathBuilder.$castTo and .$notNull to support chaining with .as()
  src/query-builder/json-path-builder.ts
  test/typings/test-d/json-traversal.test-d.ts
Labels: bug, api

#1156 DeduplicateJoinsPlugin preserves order of joins
  src/plugin/deduplicate-joins/deduplicate-joins-transformer.ts
  test/node/src/deduplicate-joins.test.ts
Labels: bug, built-in plugin

#896 Add orderBy clause support to aggregate function builder
  src/operation-node/aggregate-function-node.ts
  src/operation-node/operation-node-transformer.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/aggregate-function.test.ts
  test/typings/test-d/aggregate-function.test-d.ts
Labels: enhancement, mysql, sqlite, postgres, api
