Repository kysely-org/kysely, pull requests merged in 2024-07, with the labels that each got.

#871 add modifyEnd to insert, update and delete query builders
  src/operation-node/delete-query-node.ts
  src/operation-node/insert-query-node.ts
  src/operation-node/merge-query-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/query-node.ts
  src/operation-node/select-query-node.ts
  src/operation-node/update-query-node.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/merge-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/delete.test.ts
  test/node/src/insert.test.ts
  test/node/src/merge.test.ts
  test/node/src/update.test.ts
Labels: enhancement, api

#1073 Add additional config options to MSSQL dialect
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mssql/mssql-driver.ts
  test/node/src/test-setup.ts
Labels: enhancement, built-in dialect, mssql

#861 Migrate to new playground
  site/src/components/Playground.tsx
Labels: documentation

#1079 Support update table1, table2, ... query support. Closes #192
  site/docs/examples/update/0010-single-row.js
  site/docs/examples/update/0020-complex-values.js
  site/docs/examples/update/0030-my-sql-joins.js
  site/docs/examples/update/0030-my-sql-joins.mdx
  site/package-lock.json
  src/operation-node/update-query-node.ts
  src/parser/select-parser.ts
  src/parser/update-set-parser.ts
  src/plugin/with-schema/with-schema-transformer.ts
  src/query-builder/update-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  src/query-creator.ts
  test/node/src/update.test.ts
Labels: enhancement, mysql, api

#996 Adds `onReserveConnection` to Postgres and MySQL dialect configs
  src/dialect/mysql/mysql-dialect-config.ts
  src/dialect/mysql/mysql-driver.ts
  src/dialect/postgres/postgres-dialect-config.ts
  src/dialect/postgres/postgres-driver.ts
Labels: enhancement, mysql, postgres, built-in dialect, api

#1081 Improve relations recipe
  site/docs/recipes/0001-relations.md
Labels: documentation

#1083 Improve expressions recipe
  site/docs/recipes/0006-expressions.md
Labels: documentation

#1086 feat: add postgres range types
  src/operation-node/data-type-node.ts
Labels: enhancement, postgres, api

#1092 fix: References typo
  src/raw-builder/sql.ts
Labels: documentation
