Repository kysely-org/kysely, pull requests merged in 2024-11, with the labels that each got.

#1207 chore: add conditional exports test.
  package-lock.json
  package.json
Labels: CI

#1194 chore: enforce min TS version
  .github/workflows/test.yml
  .npmignore
  outdated-typescript.d.ts
  package-lock.json
  package.json
  test/outdated-ts/outdated-ts.test.ts
  test/outdated-ts/package-lock.json
  test/outdated-ts/package.json
  test/outdated-ts/tsconfig.json
Labels: typescript, CI

#1216 Docs: fix typo
  site/docs/examples/insert/0040-complex-values.js
  src/query-builder/insert-query-builder.ts
Labels: documentation

#1219 chore: add continuous preview releases.
  .github/workflows/preview.yml
  package-lock.json
  package.json
Labels: CI

#1262 chore: test deno 2.
  .github/workflows/test.yml
Labels: CI

#1263 chore: check jsdoc examples.
  .github/workflows/test.yml
  deno.check.d.ts
  deno.check.json
  package.json
  src/dialect/dialect-adapter.ts
  src/dialect/mssql/mssql-dialect-config.ts
  src/expression/expression-builder.ts
  src/expression/expression-wrapper.ts
  src/expression/expression.ts
  src/migration/file-migration-provider.ts
  src/migration/migrator.ts
  src/operation-node/operation-node-transformer.ts
  src/plugin/parse-json-results/parse-json-results-plugin.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/json-path-builder.ts
  src/query-builder/merge-query-builder.ts
  src/query-builder/output-interface.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/raw-builder/raw-builder.ts
  src/schema/create-table-builder.ts
  src/util/streamable.ts
Labels: CI

#1264 chore: fix jsdoc errors and add some examples, pt. 1.
  deno.check.d.ts
  src/schema/alter-table-add-index-builder.ts
  src/schema/column-definition-builder.ts
  src/schema/create-table-builder.ts
  src/util/column-type.ts
  src/util/require-all-props.ts
  src/util/type-utils.ts
Labels: documentation

#1277 chore: fix jsdoc errors and add some examples, pt. 2.
  deno.check.d.ts
  src/query-builder/function-module.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/insert-result.ts
  src/query-builder/merge-query-builder.ts
  src/query-builder/on-conflict-builder.ts
  src/query-builder/output-interface.ts
  src/query-builder/returning-interface.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  src/query-builder/where-interface.ts
  src/query-creator.ts
  src/raw-builder/raw-builder.ts
  src/raw-builder/sql.ts
  src/schema/alter-column-builder.ts
Labels: documentation

#1266 docs: clarify that after rolling back a transaction the exception gets thrown again
  src/kysely.ts
Labels: documentation

#1279 chore: fix jsdoc errors and add some examples, pt. 3.
  deno.check.d.ts
  deno.check.json
  src/dialect/dialect-adapter.ts
  src/dialect/mssql/mssql-adapter.ts
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mysql/mysql-adapter.ts
  src/dialect/postgres/postgres-adapter.ts
  src/dialect/postgres/postgres-dialect-config.ts
  src/dialect/sqlite/sqlite-adapter.ts
  src/driver/dummy-driver.ts
  src/dynamic/dynamic.ts
  src/expression/expression-builder.ts
  src/expression/expression-wrapper.ts
  src/expression/expression.ts
  src/helpers/mssql.ts
  src/helpers/mysql.ts
  src/helpers/postgres.ts
  src/helpers/sqlite.ts
  src/kysely.ts
  src/migration/migrator.ts
  src/operation-node/operation-node-transformer.ts
  src/plugin/camel-case/camel-case-plugin.ts
  src/plugin/immediate-value/immediate-value-transformer.ts
  src/plugin/kysely-plugin.ts
  src/plugin/parse-json-results/parse-json-results-plugin.ts
  src/plugin/with-schema/with-schema-transformer.ts
  src/query-builder/aggregate-function-builder.ts
  src/query-builder/delete-query-builder.ts
Labels: documentation
