Repository kysely-org/kysely, pull requests merged in 2024-04, with the labels that each got.

#940 Updating visitMergeQuery to join `WhenNode`s with a space
  src/query-compiler/default-query-compiler.ts
  test/node/src/merge.test.ts
Labels: bug, postgres, built-in dialect, mssql

#953 add `objectStrategy` option that allows to not mutate result objects/arrays @ `ParseJSONResultsPlugin`.
  package-lock.json
  src/plugin/parse-json-results/parse-json-results-plugin.ts
  test/node/src/parse-json-results-plugin.test.ts
Labels: enhancement, built-in plugin

#955 fix merge queries not being transformed.
  src/query-builder/merge-query-builder.ts
  test/node/src/camel-case.test.ts
Labels: bug, postgres, mssql

#938 fixed docs for deno
  site/docs/getting-started/Instantiation.tsx
Labels: documentation, postgres

#966 remove docker-compose file version.
  docker-compose.yml
Labels: tests

#964 add node22 @ tests.
  .github/workflows/test.yml
  package-lock.json
  package.json
  test/cloudflare-workers/package-lock.json
  test/cloudflare-workers/package.json
  test/cloudflare-workers/test.ts
Labels: tests

#972 export all operation nodes, forever.
  package.json
  scripts/check-exports.js
  src/index.ts
Labels: bug, api

#969 Fix spelling, punctuation, grammar
  CONTRIBUTING.md
  README.md
  scripts/add-deno-type-references.js
  scripts/generate-site-examples.js
  site/docs/examples/DELETE/0010-single-row.mdx
  site/docs/examples/INSERT/0010-single-row.mdx
  site/docs/examples/INSERT/0020-multiple-rows.mdx
  site/docs/examples/INSERT/0030-returning-data.mdx
  site/docs/examples/INSERT/0040-complex-values.mdx
  site/docs/examples/INSERT/0050-insert-subquery.mdx
  site/docs/examples/JOIN/0010-simple-inner-join.mdx
  site/docs/examples/JOIN/0020-aliased-inner-join.mdx
  site/docs/examples/JOIN/0030-complex-join.mdx
  site/docs/examples/JOIN/0040-subquery-join.mdx
  site/docs/examples/SELECT/0010-a-single-column.mdx
  site/docs/examples/SELECT/0020-column-with-a-table.mdx
  site/docs/examples/SELECT/0030-multiple-columns.mdx
  site/docs/examples/SELECT/0040-aliases.mdx
  site/docs/examples/SELECT/0050-complex-selections.mdx
  site/docs/examples/SELECT/0051-not-null.mdx
  site/docs/examples/SELECT/0060-function-calls.mdx
  site/docs/examples/SELECT/0070-distinct.mdx
  site/docs/examples/SELECT/0080-distinct-on.mdx
  site/docs/examples/SELECT/0090-all-columns.mdx
  site/docs/examples/SELECT/0100-all-columns-of-a-table.mdx
  site/docs/examples/SELECT/0110-nested-array.mdx
  site/docs/examples/SELECT/0120-nested-object.mdx
  site/docs/examples/UPDATE/0010-single-row.mdx
  site/docs/examples/UPDATE/0020-complex-values.mdx
  site/docs/examples/WHERE/0010-simple-where-clause.mdx
  site/docs/examples/WHERE/0020-where-in.mdx
  site/docs/examples/WHERE/0030-object-filter.mdx
  site/docs/examples/WHERE/0040-or-where.mdx
  site/docs/examples/WHERE/0050-conditional-where-calls.mdx
  site/docs/examples/WHERE/0060-complex-where-clause.mdx
  site/docs/examples/transactions/0010-simple-transaction.mdx
  site/docs/generating-types.md
  site/docs/getting-started/_types.mdx
  site/docs/intro.mdx
  site/docs/recipes/0001-relations.md
  site/docs/recipes/0002-data-types.md
  site/docs/recipes/0006-expressions.md
  site/src/components/SectionFeatures/index.tsx
  site/src/pages/index.tsx
  src/dialect/dialect-adapter-base.ts
  src/dynamic/dynamic.ts
  src/expression/expression-builder.ts
  src/helpers/mysql.ts
  src/helpers/postgres.ts
  src/plugin/camel-case/camel-case-plugin.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/function-module.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/select-query-builder.ts
  src/query-builder/update-query-builder.ts
  test/node/src/with.test.ts
Labels: documentation
