Repository kysely-org/kysely, pull requests merged in 2024-06, with the labels that each got.

#1022 ci: bump bun, test mssql in bun.
  .github/workflows/test.yml
  package-lock.json
  package.json
  test/bun/bun.lockb
  test/bun/bun.test.ts
  test/bun/package.json
Labels: mssql, CI

#1031 move `preventAwait` to `alter-column-builder`.ts.
  src/schema/alter-column-builder.ts
  src/schema/alter-table-builder.ts
Labels: bug, ready for review

#1029 feat: add the starts-with postgres comparison operator
  src/operation-node/operator-node.ts
Labels: enhancement, postgres, typescript

#1034 postgres introspection getTables handle partition tables as well.
  src/dialect/postgres/postgres-introspector.ts
  test/node/src/introspect.test.ts
Labels: enhancement, postgres, built-in dialect

#1041 fix `MssqlDialect` streaming not handling backpressure.
  package-lock.json
  package.json
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mssql/mssql-driver.ts
  test/node/src/stream.test.ts
  test/node/src/test-setup.ts
Labels: bug, built-in dialect, typescript, mssql

#1042 handle connection errors @ `MssqlDriver`.
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mssql/mssql-driver.ts
  test/node/src/disconnects.test.ts
Labels: bug, built-in dialect, mssql

#1043 ci: install only chromium
  .github/workflows/test.yml
Labels: CI

#993 docs: add comments for `UpdateResult`
  src/driver/database-connection.ts
  src/query-builder/update-result.ts
Labels: documentation

#965 bump TypeScript to v5.5.
  package-lock.json
  package.json
Labels: typescript, tests

#1048 fix mssql createPerson example.
  site/docs/getting-started/Querying.tsx
Labels: documentation, mssql

#1057 docs: remove remaining react imports.
  site/src/components/Playground.tsx
  site/src/components/SectionFeatures/index.tsx
Labels: documentation

#1058 docs: fix `values` example no compiling.
  site/docs/recipes/0010-extending-kysely.md
Labels: documentation

#943 ci: split jobs.
  .github/workflows/test.yml
Labels: ready for review, tests, CI

#902 fix `InferResult` not working for merge queries.
  src/query-builder/merge-query-builder.ts
  test/typings/test-d/infer-result.test-d.ts
Labels: bug, typescript, ready for review
