Repository kysely-org/kysely, pull requests merged in 2024-03, with the labels that each got.

#911 Fix typo on timetz regex
  src/operation-node/data-type-node.ts
  test/node/src/schema.test.ts
Labels: bug, postgres

#828 add `OUTPUT` clause support.
  src/dialect/dialect-adapter-base.ts
  src/dialect/dialect-adapter.ts
  src/dialect/mssql/mssql-adapter.ts
  src/index.ts
  src/operation-node/delete-query-node.ts
  src/operation-node/insert-query-node.ts
  src/operation-node/merge-query-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/operation-node.ts
  src/operation-node/output-node.ts
  src/operation-node/query-node.ts
  src/operation-node/update-query-node.ts
  src/parser/returning-parser.ts
  src/query-builder/delete-query-builder.ts
  src/query-builder/insert-query-builder.ts
  src/query-builder/merge-query-builder.ts
  src/query-builder/output-interface.ts
  src/query-builder/returning-interface.ts
  src/query-builder/update-query-builder.ts
  src/query-compiler/default-query-compiler.ts
  test/node/src/delete.test.ts
  test/node/src/insert.test.ts
  test/node/src/merge.test.ts
  test/node/src/test-setup.ts
  test/node/src/update.test.ts
  test/typings/test-d/delete-query-builder.test-d.ts
  test/typings/test-d/insert.test-d.ts
  test/typings/test-d/merge.test-d.ts
Labels: enhancement, api, mssql

#921 Added `clearGroupBy()`
  src/operation-node/select-query-node.ts
  src/query-builder/select-query-builder.ts
  test/node/src/clear.test.ts
Labels: enhancement, api

#927 fix SQLite import @ getting started.
  site/docs/getting-started/Instantiation.tsx
Labels: documentation, sqlite
