Repository kysely-org/kysely, pull requests merged in 2024-10, with the labels that each got.

#1127 chore: bump TypeScript to 5.6.
  package-lock.json
  package.json
Labels: typescript

#962 add `ControlledTransaction`.
  scripts/copy-interface-documentation.js
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mssql/mssql-driver.ts
  src/dialect/mysql/mysql-driver.ts
  src/dialect/postgres/postgres-driver.ts
  src/dialect/sqlite/sqlite-driver.ts
  src/driver/driver.ts
  src/driver/dummy-driver.ts
  src/driver/runtime-driver.ts
  src/kysely.ts
  src/parser/savepoint-parser.ts
  src/query-executor/query-executor-base.ts
  src/util/provide-controlled-connection.ts
  test/node/src/controlled-transaction.test.ts
Labels: enhancement, custom dialect, built-in dialect, api, ready for review

#1177 docs: support light mode.
  site/docusaurus.config.ts
  site/src/components/Playground.tsx
  site/src/components/SectionFeatures/index.tsx
  site/src/css/custom.css
  site/src/pages/index.tsx
Labels: documentation

#1179 docs: fix weird default state showing dark and light elements.
  site/docs/playground.mdx
  site/src/components/Playground.module.css
  site/src/components/Playground.tsx
  site/src/components/SectionFeatures/index.tsx
  site/src/components/SectionFeatures/styles.module.css
  site/src/components/SectionQuotes/Quote.tsx
  site/src/components/SectionQuotes/index.tsx
  site/src/components/SectionQuotes/quotes.ts
  site/src/components/SectionQuotes/styles.module.css
  site/src/pages/index.module.css
  site/src/pages/index.tsx
Labels: documentation

#1178 fix(docs): add missing import to migrations example script
  site/docs/migrations.mdx
Labels: documentation

#1182 docs: refresh quotes.
  site/src/components/SectionQuotes/Quote.tsx
  site/src/components/SectionQuotes/quotes.ts
  site/src/components/SectionQuotes/styles.module.css
  site/static/img/avatars/bekacru.png
  site/static/img/avatars/capaj.png
  site/static/img/avatars/catalin.png
  site/static/img/avatars/gudmundur.png
  site/static/img/avatars/guga.png
  site/static/img/avatars/harminder.jpeg
  site/static/img/avatars/harminder.png
  site/static/img/avatars/marvin.png
  site/static/img/avatars/niels.png
Labels: documentation

#1183 docs: fix stackblitz theme out of sync.
  site/src/pages/index.module.css
  site/src/pages/index.tsx
Labels: documentation

#1185 docs: rework features list.
  site/src/components/SectionFeatures/index.tsx
Labels: documentation

#1167 `await using kysely = new Kysely()` support.
  src/kysely.ts
  test/node/src/async-dispose.test.ts
  test/node/tsconfig.json
Labels: enhancement, api, typescript

#1188 docs: `MERGE` examples
  package.json
  scripts/generate-site-examples.js
  site/docs/examples/cte/_category_.json
  site/docs/examples/merge/0010-source-row-existence.js
  site/docs/examples/merge/0010-source-row-existence.mdx
  site/docs/examples/merge/0020-temporary-changes-table.js
  site/docs/examples/merge/0020-temporary-changes-table.mdx
  site/docs/examples/merge/_category_.json
  site/docs/examples/select/0070-distinct.mdx
  site/docs/examples/transactions/_category_.json
  site/package-lock.json
  site/package.json
  site/src/components/Playground.tsx
  site/src/css/custom.css
  src/query-builder/select-query-builder.ts
  src/query-creator.ts
Labels: documentation

#1192 ci: test against older TypeScript versions.
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/query-builder/merge-query-builder.ts
  test/node/src/test-setup.ts
  test/node/src/transaction.test.ts
  test/node/tsconfig.json
Labels: typescript, CI

#1193 fix TS backwards compat following `ControlledTransaction`.
  .github/workflows/test.yml
  package-lock.json
  package.json
  scripts/exclude-test-files-for-backwards-compat.mts
  src/kysely.ts
  src/parser/savepoint-parser.ts
  test/node/src/async-dispose.test.ts
  test/node/src/controlled-transaction.test.ts
  test/node/tsconfig.json
Labels: typescript, CI

#1197 docs: add prerequisites section in "getting started".
  site/docs/getting-started.mdx
  site/docs/getting-started/_prerequisites.mdx
Labels: documentation, typescript
