Repository kysely-org/kysely, pull requests merged in 2025-09, with the labels that each got.

#1577 chore: bump deps.
  .github/workflows/bench.yml
  .github/workflows/compare.yml
  .github/workflows/preview.yml
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
  site/package.json
  test/bun/bun.lock
  test/bun/package.json
  test/cloudflare-workers/package.json
  test/deno/deno.json
  test/deno/deno.lock
Labels: CI, dependencies

#1579 fix(ExpressionBuilder): improper custom operator support in `eb()`.
  src/expression/expression-builder.ts
  test/typings/test-d/expression.test-d.ts
Labels: bug, enhancement, api, typescript

#1580 fix: auto rollback only if transaction begun.
  pnpm-workspace.yaml
  src/kysely.ts
  test/node/src/transaction.test.ts
Labels: bug, internal

#1550 fix: filter schemas the current user does not have access to in postres introspector
  src/dialect/postgres/postgres-introspector.ts
Labels: bug, postgres, introspection

#1590 chore: add SECURITY.md.
  SECURITY.md
Labels: documentation

#1600 chore: bumps dependencies.
  package.json
  pnpm-lock.yaml
  site/package.json
  test/bun/bun.lock
  test/bun/package.json
  test/cloudflare-workers/package.json
  test/composite-ts/package-lock.json
  test/composite-ts/package.json
  test/deno/deno.json
  test/deno/deno.lock
Labels: documentation, tests, CI
