Repository kysely-org/kysely, pull requests merged in 2025-05, with the labels that each got.

#1450 chore: bye bye node 18.
  .github/workflows/preview.yml
  .github/workflows/test.yml
  package.json
Labels: CI

#1451 chore: bump deps, dump `tsx` for Node.js native TS.
  .node-version
  .nvmrc
  package-lock.json
  package.json
  scripts/tsconfig.json
  test/cloudflare-workers/package.json
  test/node/src/error-stack.test.ts
  test/node/src/test-setup.ts
  test/ts-benchmarks/index.ts
  test/ts-benchmarks/package.json
Labels: tests, CI

#1460 Update plugins.md: fix broken link
  site/docs/plugins.md
Labels: documentation

#1462 chore(CI): replace Node.js v23 with v24.
  .github/workflows/test.yml
Labels: CI

#1467 chore(CI): add native typescript type checks.
  .github/workflows/test.yml
Labels: typescript, CI

#1471 chore: move pkg-pr-new to workflow only.
  .github/workflows/preview.yml
  package-lock.json
  package.json
Labels: CI
