Repository kysely-org/kysely, pull requests merged in 2025-04, with the labels that each got.

#1414 enhance contribution @ readme.
  README.md
Labels: documentation

#1392 feat: escape single quotes in string literals.
  src/query-compiler/default-query-compiler.ts
  test/node/src/sql-injection.test.ts
Labels: enhancement, breaking change, internal

#1426 pg introspector - Wrap schema.table in double quotes for case handling
  src/dialect/postgres/postgres-introspector.ts
  test/node/src/introspect.test.ts
Labels: bug, postgres, built-in dialect

#1435 fix: SQLite's introspector is printing deprecation errors for `orderBy(array)`.
  src/dialect/sqlite/sqlite-introspector.ts
  src/query-builder/order-by-interface.ts
Labels: bug, sqlite, built-in dialect

#1436 ensure jsdocs check's dts is source of truth for docs examples.
  scripts/generate-site-examples.js
  site/docs/examples/cte/0010-simple-selects.mdx
  site/docs/examples/cte/0020-inserts-updates-and-deletions.mdx
  site/docs/examples/delete/0010-single-row.mdx
  site/docs/examples/insert/0010-single-row.mdx
  site/docs/examples/insert/0020-multiple-rows.mdx
  site/docs/examples/insert/0030-returning-data.mdx
  site/docs/examples/insert/0040-complex-values.mdx
  site/docs/examples/insert/0050-insert-subquery.mdx
  site/docs/examples/join/0010-simple-inner-join.mdx
  site/docs/examples/join/0020-aliased-inner-join.mdx
  site/docs/examples/join/0030-complex-join.mdx
  site/docs/examples/join/0040-subquery-join.mdx
  site/docs/examples/merge/0010-source-row-existence.mdx
  site/docs/examples/merge/0020-temporary-changes-table.mdx
  site/docs/examples/select/0010-a-single-column.mdx
  site/docs/examples/select/0020-column-with-a-table.mdx
  site/docs/examples/select/0030-multiple-columns.mdx
  site/docs/examples/select/0040-aliases.mdx
  site/docs/examples/select/0050-complex-selections.mdx
  site/docs/examples/select/0051-not-null.mdx
  site/docs/examples/select/0060-function-calls.mdx
  site/docs/examples/select/0070-distinct.mdx
  site/docs/examples/select/0080-distinct-on.mdx
  site/docs/examples/select/0090-all-columns.mdx
  site/docs/examples/select/0100-all-columns-of-a-table.mdx
  site/docs/examples/select/0110-nested-array.mdx
  site/docs/examples/select/0120-nested-object.mdx
  site/docs/examples/transactions/0010-simple-transaction.mdx
  site/docs/examples/transactions/0011-controlled-transaction.mdx
  site/docs/examples/transactions/0012-controlled-transaction-w-savepoints.mdx
  site/docs/examples/update/0010-single-row.mdx
  site/docs/examples/update/0020-complex-values.mdx
  site/docs/examples/update/0030-my-sql-joins.mdx
  site/docs/examples/where/0010-simple-where-clause.mdx
  site/docs/examples/where/0020-where-in.mdx
  site/docs/examples/where/0030-object-filter.mdx
  site/docs/examples/where/0040-or-where.mdx
  site/docs/examples/where/0050-conditional-where-calls.mdx
  site/docs/examples/where/0060-complex-where-clause.mdx
  site/docs/playground.mdx
  site/package-lock.json
  site/package.json
  site/src/components/Playground.tsx
  site/src/components/playground-example-types.ts
Labels: bug, documentation
