Repository kysely-org/kysely, pull requests merged in 2025-03, with the labels that each got.

#1382 fix: no logging in streams.
  src/driver/runtime-driver.ts
  src/util/log.ts
  test/node/src/logging.test.ts
Labels: bug

#1388 refactor: extract `validateConnections` and `resetConnectionsOnRelease` to root of config, flip default `resetConnectionsOnRelease` behavior.
  src/dialect/mssql/mssql-dialect-config.ts
  src/dialect/mssql/mssql-driver.ts
  test/node/src/test-setup.ts
Labels: built-in dialect, breaking change, mssql

#1395 fix: allow empty array for sql.join
  src/raw-builder/sql.ts
Labels: bug

#1406 Fix ctrl transaction mutation issues
  src/kysely.ts
  src/query-executor/query-executor-base.ts
  src/util/provide-controlled-connection.ts
Labels: enhancement, internal

#1407 add support for deferrable constraints. Closes #224
  src/index.ts
  src/operation-node/constraint-node.ts
  src/operation-node/foreign-key-constraint-node.ts
  src/operation-node/operation-node-transformer.ts
  src/operation-node/operation-node-visitor.ts
  src/operation-node/primary-key-constraint-node.ts
  src/operation-node/unique-constraint-node.ts
  src/query-compiler/default-query-compiler.ts
  src/schema/alter-table-add-foreign-key-constraint-builder.ts
  src/schema/alter-table-builder.ts
  src/schema/check-constraint-builder.ts
  src/schema/create-table-builder.ts
  src/schema/foreign-key-constraint-builder.ts
  src/schema/primary-key-constraint-builder.ts
  src/schema/unique-constraint-builder.ts
  test/node/src/schema.test.ts
  test/typings/test-d/json-traversal.test-d.ts
  test/typings/test-d/where.test-d.ts
Labels: enhancement, sqlite, postgres, api, deprecation
